/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#5f5e5e",
        "outline": "#777777",
        "on-primary-fixed-variant": "#e5e2e1",
        "surface-container-low": "#f3f3f3",
        "on-background": "#1a1c1c",
        "on-tertiary-container": "#ffffff",
        "background": "#FAFAFA",
        "on-secondary-fixed-variant": "#3b3b3b",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#e2e2e2",
        "error-container": "#ffdad6",
        "surface": "#FAFAFA",
        "secondary-fixed": "#c6c6c6",
        "on-tertiary": "#e2e2e2",
        "surface-container-highest": "#e2e2e2",
        "secondary": "#5e5e5e",
        "primary": "#1A1A1A",
        "on-error-container": "#410002",
        "tertiary": "#3b3b3b",
        "on-surface": "#1a1c1c",
        "on-secondary-container": "#1b1b1b",
        "inverse-on-surface": "#f0f1f1",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#474746",
        "on-tertiary-fixed": "#ffffff",
        "on-primary-container": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "tertiary-container": "#747474",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#474747",
        "surface-container": "#eeeeee",
        "secondary-container": "#d4d4d4",
        "secondary-fixed-dim": "#ababab",
        "tertiary-fixed": "#5e5e5e",
        "primary-fixed": "#5f5e5e",
        "on-surface-variant": "#474747",
        "inverse-surface": "#2f3131",
        "on-primary-fixed": "#ffffff",
        "outline-variant": "#c6c6c6",
        "primary-container": "#3c3b3b",
        "on-secondary-fixed": "#1b1b1b",
        "on-primary": "#FAFAFA",
        "surface-variant": "#e2e2e2",
        "inverse-primary": "#c8c6c5",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        // Kept for backward compatibility if missed during refactor
        'brand': '#FF5733',
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "noto-serif": ["Noto Serif", "serif"],
        "body": ["Inter", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
        "label": ["Work Sans", "sans-serif"],
        "work-sans": ["Work Sans", "sans-serif"],
        // Defaults
        "serif": ["Noto Serif", "serif"],
        "sans": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "none": "0px",
        "sm": "0px",
        "DEFAULT": "0px",
        "md": "0px",
        "lg": "0px",
        "xl": "0px",
        "2xl": "0px",
        "3xl": "0px",
        "full": "9999px" // Except for full rounds (circles, e.g. floating dots)
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 4s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-15px)' },
        }
      }
    },
  },
  plugins: [],
}
